import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
  fullName: {
    type: String,
    required: true,
  },
  emailAddress: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
 role: {
  type: String,
  enum: [
    "AI Engineer",
    "Prompt Engineer",
    "Machine Learning Engineer",
    "Data Scientist",
    "Data Engineer",
    "Cloud Architect",
    "Cloud Security Engineer",
    "Cybersecurity Specialist",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Blockchain Developer",
    "Web3 Developer",
    "AR/VR Developer",
    "Metaverse Architect",
    "Quantum Computing Researcher",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "Game Developer",
    "XR Developer",
    "Product Manager",
    "Technical Product Manager",
    "Growth Product Manager",
    "User Experience Designer",
    "UX Researcher",
    "UI Designer",
    "Interaction Designer",
    "Motion Designer",
    "3D Artist",
    "AI Product Designer",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Robotics Engineer",
    "Automation Engineer",
    "Edge Computing Engineer",
    "IoT Developer",
    "Digital Twin Engineer",
    "Technical Writer",
    "Technical Evangelist",
    "Developer Advocate",
    "Open Source Maintainer",
    "Security Researcher",
    "Penetration Tester",
    "Vulnerability Analyst",
    "Compliance Engineer",
    "MLOps Engineer",
    "AI Ethicist",
    "AI Policy Specialist",
    "Sustainability Engineer",
    "Climate Data Analyst",
    "Esports Manager",
    "Game Streamer",
    "Content Creator",
    "Influencer Marketing Manager",
    "Digital Marketing Strategist",
    "Growth Hacker",
    "SEO Specialist",
    "Brand Strategist",
    "No-Code Developer",
    "Low-Code Developer",
    "Platform Engineer",
    "Fintech Product Manager",
    "Crypto Analyst",
    "NFT Strategist",
    "Community Manager",
    "Customer Success Manager",
    "Solutions Architect",
    "Technical Program Manager",
    "Revenue Operations Specialist",
    "AI Trainer",
    "AI Data Labeler",
    "Video Producer",
    "Podcast Producer",
    "Sound Designer",
    "VR Storyteller",
    "Digital Illustrator",
    "Chief Technology Officer",
    "Chief Product Officer",
    "Chief Marketing Officer",
    "Innovation Manager",
    "Research Scientist",
    "Bioinformatics Engineer",
    "Health Tech Specialist",
    "Legal Tech Consultant",
    "Ethical Hacker",
    "SaaS Operations Engineer",
    "Remote Work Specialist",
    "Employee Experience Designer",
    "AI Operations Manager",
    "Automation Strategist"
  ],
  required: true,
}
,
  skills: {
    type: [String],
    default: [],
  },
}, { timestamps: true });

const User = mongoose.model('User', userSchema);
export default User;
